# Generated by Django 4.2.24 on 2025-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='clasecancelacion',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='clasecancelacion',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='clasecancelacion',
            name='reservado_por',
        ),
        migrations.RemoveField(
            model_name='incumplimiento',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='incumplimiento',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='incumplimiento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='ClaseCancelacion',
        ),
        migrations.DeleteModel(
            name='Incumplimiento',
        ),
    ]
