# Generated by Django 4.2.24 on 2025-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_asistencia_clase_remove_asistencia_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='semestre_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='semestre_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
