# Generated by Django 4.2.25 on 2025-10-22 16:45

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_semestre_fin_reserva_semestre_inicio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='reservas_no_solapamiento',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaestadohistorial',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservaestadohistorial',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado', 'aprobado')), expressions=[(models.F('espacio'), '='), (models.F('periodo'), '&&')], name='reservas_no_solapamiento'),
        ),
    ]
