# Generated by Django 4.2.25 on 2025-11-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_reserva_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE reservas_reserva DROP CONSTRAINT IF EXISTS reservas_no_solapamiento;",
            reverse_sql="",
        ),
    ]
