version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: uisrooms
      POSTGRES_PASSWORD: uisrooms123
      POSTGRES_DB: uisrooms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uisrooms"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
