# Generated by Django 4.2.24 on 2025-09-25 19:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadEspacio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField(blank=True, help_text='0=Lunes ... 6=Domingo; null si excepción por fecha', null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('recurrente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'disponibilidad_espacio',
                'verbose_name_plural': 'disponibilidades_espacio',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('auditorio', 'Auditorio'), ('salon', 'Salón'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller'), ('otro', 'Otro')], default='salon', max_length=20)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True)),
                ('recursos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'espacio',
                'verbose_name_plural': 'espacios',
            },
        ),
        migrations.CreateModel(
            name='EspacioBitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=150)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'espacio_bitacora',
                'verbose_name_plural': 'espacio_bitacora',
            },
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['codigo'], name='espacios_es_codigo_21a53c_idx'),
        ),
        migrations.AddField(
            model_name='disponibilidadespacio',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='espacios.espacio'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadespacio',
            index=models.Index(fields=['espacio'], name='espacios_di_espacio_877a7c_idx'),
        ),
    ]
