# Generated by Django 4.2.24 on 2025-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='tipo',
            field=models.CharField(choices=[('aula', 'Aulas'), ('laboratorio', 'Laboratorios'), ('sala', 'Salas')], default='aula', max_length=20),
        ),
    ]
