# Generated by Django 4.2.24 on 2025-09-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestada', 'Prestada'), ('perdida', 'Perdida'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaves', to='espacios.espacio')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'llave',
                'verbose_name_plural': 'llaves',
            },
        ),
        migrations.CreateModel(
            name='LlaveRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('registro', 'Registro'), ('devolucion', 'Devolución')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='llaves.llave')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'llave_registro',
                'verbose_name_plural': 'llaves_registro',
            },
        ),
    ]
