# Generated by Django 5.2.6 on 2025-09-25 15:59
from django.db import migrations

class Migration(migrations.Migration):

    initial = True
    dependencies = [
        # Si ya tienes migraciones previas en 'usuarios', cambia esto
        # por ('usuarios', '0001_initial') o la última migración existente.
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gist;"),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
    ]
