# Generated by Django 4.2.24 on 2025-09-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('agenda', 'Agenda'), ('reserva', 'Reserva'), ('sistema', 'Sistema'), ('incidencia', 'Incidencia')], default='sistema', max_length=30)),
                ('mensaje', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enviado', models.BooleanField(default=False)),
                ('leido', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'indexes': [models.Index(fields=['destinatario'], name='notificacio_destina_46d4a0_idx')],
            },
        ),
    ]
