# Generated by Django 4.2.24 on 2025-10-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_alter_espacio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='ubicacion',
            field=models.CharField(choices=[('primer_piso', 'Primer piso'), ('segundo_piso', 'Segundo piso'), ('tercer_piso', 'Tercer piso')], default='primer_piso', max_length=20),
        ),
    ]
