# Generated by Django 4.2.24 on 2025-10-20 12:42

from datetime import time

from django.db import migrations, models


DEFAULT_START = time(6, 0)
DEFAULT_END = time(20, 0)


def crear_horario_base(apps, schema_editor):
    Espacio = apps.get_model('espacios', 'Espacio')
    DisponibilidadEspacio = apps.get_model('espacios', 'DisponibilidadEspacio')

    for espacio in Espacio.objects.all():
        if DisponibilidadEspacio.objects.filter(espacio=espacio, es_bloqueo=False).exists():
            continue

        registros = [
            DisponibilidadEspacio(
                espacio=espacio,
                dia_semana=dia,
                hora_inicio=DEFAULT_START,
                hora_fin=DEFAULT_END,
                recurrente=True,
                es_bloqueo=False,
                observaciones='Horario base (6:00 - 20:00)',
            )
            for dia in range(7)
        ]
        DisponibilidadEspacio.objects.bulk_create(registros)


def revertir_horario_base(apps, schema_editor):
    DisponibilidadEspacio = apps.get_model('espacios', 'DisponibilidadEspacio')
    DisponibilidadEspacio.objects.filter(
        es_bloqueo=False,
        observaciones='Horario base (6:00 - 20:00)',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_alter_espacio_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadespacio',
            name='es_bloqueo',
            field=models.BooleanField(default=False, help_text='True indica un horario bloqueado/no disponible'),
        ),
        migrations.RunPython(crear_horario_base, reverse_code=revertir_horario_base),
    ]
