# Generated by Django 4.2.24 on 2025-09-25 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_initial'),
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('documento', 'Documento'), ('electronico', 'Electrónico'), ('ropa', 'Ropa'), ('otro', 'Otro')], max_length=50, null=True)),
                ('fecha_encontrado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='encontrado', max_length=50)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('encontrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.usuario')),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.usuario')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.espacio')),
            ],
            options={
                'verbose_name': 'objeto_perdido',
                'verbose_name_plural': 'objetos_perdidos',
            },
        ),
    ]
