# Generated by Django 4.2.24 on 2025-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llaves', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LlaveRegistro',
        ),
    ]
